/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  knowledgeSidebar: [
    "overview",
    {
      type: "category",
      label: "大数据",
      link: {
        type: "generated-index",
        title: "大数据",
        description: "覆盖流处理、存储、计算和系统设计等知识主题与工程问题。",
        slug: "/category/big-data",
      },
      items: [{ type: "autogenerated", dirName: "bigdata" }],
    },
    {
      type: "category",
      label: "AI Agent",
      link: {
        type: "generated-index",
        title: "AI Agent",
        description: "覆盖框架、协议、模式和生产环境中的 Agent 工程知识。",
        slug: "/category/ai-agents",
      },
      items: [{ type: "autogenerated", dirName: "ai-agent" }],
    },
    {
      type: "category",
      label: "大模型基础",
      link: {
        type: "generated-index",
        title: "大模型基础",
        description: "覆盖 Transformer、Tokenizer、预训练、后训练、推理、Prompt、Embedding、RAG 与评估等基础主题。",
        slug: "/category/llm-foundations",
      },
      items: [{ type: "autogenerated", dirName: "llm-foundations" }],
    },
  ],
};

module.exports = sidebars;
